### PR TITLE
Documentation and code refresh

### PR DESCRIPTION
**Pull request by markoprodanovic**
Made some minor changes to project structure. Made courses.csv and entitlements.csv single file titled: courses.csv. User filtering is optional and can be done with the inclusion of a user_id column. Courses.csv must then be joined with data in Tableau. Updated README.

### CODE REVIEW

**Comment by markoprodanovic** [comment]
Hey @alisonmyers. I've blended `entitlements.csv` and `courses.csv` into a single `courses.csv` file. `user_id` column is optional.

Tableau has since changed how relationships work between Tables and now I'm a bit less familiar with it. See the README under "Connecting to Tableau", I've tagged you and asked for tips. How do we get that same "join" type filtering in Tableau's new "relationship" feature?

This is how we used to do it:
joins

**Comment by alisonmyers** [comment]
can we call it course_entitlements (?)

**Comment by markoprodanovic** [comment]
sure!

**Comment by markoprodanovic** [comment]
**Would close #8**
**Would close #10**

**Comment by alisonmyers** [comment]
your pull request is still a draft - let me know if you are ready for review

**Review by alisonmyers — CHANGES_REQUESTED** [review]
I think I would prefer that the main.py is called something related to module_progress (update_module_progress.py) ... I know it's not the best but I think it's a good thing for our ops to be more specific when they run this

**Comment by markoprodanovic** [comment]
Made change above. Merge ready?

**Pull request merged**
